services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: "0"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Default email for pgAdmin login
      PGADMIN_DEFAULT_PASSWORD: admin           # Default password for pgAdmin login
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - monitoring-network
    depends_on:
      - postgres

volumes:
  grafana-storage:
  postgres-data:
  pgadmin-data:

networks:
  monitoring-network: